// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockOptionsApi.Models;

namespace StockOptionsApi.Migrations
{
    [DbContext(typeof(OptionsDBContext))]
    [Migration("20210809192759_StockTable")]
    partial class StockTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockOptionsApi.Models.Option", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("commision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("contracts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("daysToExpiry")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("delta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("expiryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("premium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("stockPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("strikePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ticker")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("StockOptionsApi.Models.Stock", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ticker")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
