// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockOptionsApi.Models;

namespace StockOptionsApi.Migrations
{
    [DbContext(typeof(OptionsDBContext))]
    [Migration("20210802212403_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockOptionsApi.Models.Option", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("commision")
                        .HasColumnType("int");

                    b.Property<int>("contracts")
                        .HasColumnType("int");

                    b.Property<string>("daysToExpiry")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("delta")
                        .HasColumnType("int");

                    b.Property<DateTime>("expiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("premium")
                        .HasColumnType("int");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("stockPrice")
                        .HasColumnType("int");

                    b.Property<int>("strikePrice")
                        .HasColumnType("int");

                    b.Property<string>("ticker")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
